# ステージング開発環境用の定義

server:
  servlet.context-path: /stg-todoapi
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2
    username: sa
    password: ''
  sql:
    init:
      enabled: true
      encoding: UTF8
      schema-locations: classpath:develop-resources/schema.sql
      data-locations: classpath:develop-resources/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mail:
    host: localhost
    port: 3025
    properties:
      from: hoge@example.com
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
